version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-tier
    volumes:
      - ./mongodbdata:/mongo

  ztffps:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_DB_LOCATION_DOCKER=mongo
    networks:
      - app-tier
    command:
      uvicorn api:ztffps_api --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./ZTFDATA:/ZTFDATA

networks:
  app-tier:
    driver: bridge

volumes:
  mongodbdata:
  ZTFDATA:
