#!/bin/bash

cmd="slackbot.py -channel $1 -thread $2 "
echo $cmd
#screen -d -m
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
bash -c "fps_slackbot -channel $1 -thread $2 -verbose"
